// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/controller-manager-library/pkg/apis/gardenextensions/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	labels "k8s.io/apimachinery/pkg/labels"
	schema "k8s.io/apimachinery/pkg/runtime/schema"
	types "k8s.io/apimachinery/pkg/types"
	watch "k8s.io/apimachinery/pkg/watch"
	testing "k8s.io/client-go/testing"
)

// FakeDNSs implements DNSInterface
type FakeDNSs struct {
	Fake *FakeGardenextensionsV1alpha1
	ns   string
}

var dnssResource = schema.GroupVersionResource{Group: "gardenextensions", Version: "v1alpha1", Resource: "dnss"}

var dnssKind = schema.GroupVersionKind{Group: "gardenextensions", Version: "v1alpha1", Kind: "DNS"}

// Data takes name of the dNS, and returns the corresponding dNS object, and an error if there is any.
func (c *FakeDNSs) Get(name string, options v1.GetOptions) (result *v1alpha1.DNS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewGetAction(dnssResource, c.ns, name), &v1alpha1.DNS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNS), err
}

// List takes label and field selectors, and returns the list of DNSs that match those selectors.
func (c *FakeDNSs) List(opts v1.ListOptions) (result *v1alpha1.DNSList, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewListAction(dnssResource, dnssKind, c.ns, opts), &v1alpha1.DNSList{})

	if obj == nil {
		return nil, err
	}

	label, _, _ := testing.ExtractFromListOptions(opts)
	if label == nil {
		label = labels.Everything()
	}
	list := &v1alpha1.DNSList{ListMeta: obj.(*v1alpha1.DNSList).ListMeta}
	for _, item := range obj.(*v1alpha1.DNSList).Items {
		if label.Matches(labels.Set(item.Labels)) {
			list.Items = append(list.Items, item)
		}
	}
	return list, err
}

// Watch returns a watch.Interface that watches the requested dNSs.
func (c *FakeDNSs) Watch(opts v1.ListOptions) (watch.Interface, error) {
	return c.Fake.
		InvokesWatch(testing.NewWatchAction(dnssResource, c.ns, opts))

}

// Create takes the representation of a dNS and creates it.  Returns the server's representation of the dNS, and an error, if there is any.
func (c *FakeDNSs) Create(dNS *v1alpha1.DNS) (result *v1alpha1.DNS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewCreateAction(dnssResource, c.ns, dNS), &v1alpha1.DNS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNS), err
}

// Update takes the representation of a dNS and updates it. Returns the server's representation of the dNS, and an error, if there is any.
func (c *FakeDNSs) Update(dNS *v1alpha1.DNS) (result *v1alpha1.DNS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateAction(dnssResource, c.ns, dNS), &v1alpha1.DNS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNS), err
}

// UpdateStatus was generated because the type contains a Status member.
// Add a +genclient:noStatus comment above the type to avoid generating UpdateStatus().
func (c *FakeDNSs) UpdateStatus(dNS *v1alpha1.DNS) (*v1alpha1.DNS, error) {
	obj, err := c.Fake.
		Invokes(testing.NewUpdateSubresourceAction(dnssResource, "status", c.ns, dNS), &v1alpha1.DNS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNS), err
}

// Delete takes name of the dNS and deletes it. Returns an error if one occurs.
func (c *FakeDNSs) Delete(name string, options *v1.DeleteOptions) error {
	_, err := c.Fake.
		Invokes(testing.NewDeleteAction(dnssResource, c.ns, name), &v1alpha1.DNS{})

	return err
}

// DeleteCollection deletes a collection of objects.
func (c *FakeDNSs) DeleteCollection(options *v1.DeleteOptions, listOptions v1.ListOptions) error {
	action := testing.NewDeleteCollectionAction(dnssResource, c.ns, listOptions)

	_, err := c.Fake.Invokes(action, &v1alpha1.DNSList{})
	return err
}

// Patch applies the patch and returns the patched dNS.
func (c *FakeDNSs) Patch(name string, pt types.PatchType, data []byte, subresources ...string) (result *v1alpha1.DNS, err error) {
	obj, err := c.Fake.
		Invokes(testing.NewPatchSubresourceAction(dnssResource, c.ns, name, data, subresources...), &v1alpha1.DNS{})

	if obj == nil {
		return nil, err
	}
	return obj.(*v1alpha1.DNS), err
}
