#!/bin/bash
#
# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

export REPO_ROOT=$(dirname $0)/..

export VGOPATH="${VGOPATH}"

# setup virtual GOPATH
source "${REPO_ROOT}/hack"/vgopath-setup.sh

CODE_GEN_DIR=$(go list -m -f '{{.Dir}}' k8s.io/code-generator)

rm -f ${GOPATH}/bin/*-gen || true

# We need to explicitly pass GO111MODULE=off to k8s.io/code-generator as it is significantly slower otherwise,
# see https://github.com/kubernetes/code-generator/issues/100.
export GO111MODULE=off

echo "generating deepcopy, defaulter ($PWD)"
bash "${CODE_GEN_DIR}"/generate-internal-groups.sh \
  deepcopy,defaulter \
  github.com/gardener/controller-manager-library/pkg/controllermanager/webhook/conversion/client \
  github.com/gardener/controller-manager-library/pkg/controllermanager/webhook/conversion/api \
  github.com/gardener/controller-manager-library/pkg/controllermanager/webhook/conversion/api \
  ":v1,v1beta1" \
  --go-header-file "${REPO_ROOT}/hack/LICENSE_BOILERPLATE.txt"

echo "generating conersion ($PWD)"
bash "${CODE_GEN_DIR}"/generate-internal-groups.sh \
  conversion \
  github.com/gardener/controller-manager-library/pkg/controllermanager/webhook/conversion/client \
  github.com/gardener/controller-manager-library/pkg/controllermanager/webhook/conversion/api \
  github.com/gardener/controller-manager-library/pkg/controllermanager/webhook/conversion/api \
  ":v1,v1beta1" \
  --extra-peer-dirs=github.com/gardener/controller-manager-library/pkg/controllermanager/webhook/conversion/api,github.com/gardener/controller-manager-library/pkg/controllermanager/webhook/conversion/api/v1,github.com/gardener/controller-manager-library/pkg/controllermanager/webhook/conversion/api/v1beta1,k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/conversion,k8s.io/apimachinery/pkg/runtime \
  --go-header-file "${REPO_ROOT}/hack/LICENSE_BOILERPLATE.txt"

echo done