#!/bin/bash
#
# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -e

export REPO_ROOT=$(dirname $0)/..

export VGOPATH="${VGOPATH}"

# setup virtual GOPATH
source "${REPO_ROOT}/hack"/vgopath-setup.sh

CODE_GEN_DIR=$(go list -m -f '{{.Dir}}' k8s.io/code-generator)
source "${CODE_GEN_DIR}/kube_codegen.sh"

rm -f ${GOPATH}/bin/*-gen || true

kube::codegen::gen_helpers \
  --boilerplate "${REPO_ROOT}/hack/LICENSE_BOILERPLATE.txt" \
    --extra-peer-dir k8s.io/apimachinery/pkg/apis/meta/v1 \
    --extra-peer-dir k8s.io/apimachinery/pkg/conversion \
  "${REPO_ROOT}/pkg/controllermanager/webhook/conversion"

echo done