#!/bin/bash
#
# SPDX-FileCopyrightText: 2019 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

rm -f $GOPATH/bin/*-gen

PROJECT_ROOT=$(dirname $0)/../../../..

echo "*** generate deepcopy, defaulter ($PWD)"
bash "${PROJECT_ROOT}"/vendor/k8s.io/code-generator/generate-internal-groups.sh \
  deepcopy,defaulter \
  github.com/gardener/controller-manager-library/pkg/controllermanager/examples/client \
  github.com/gardener/controller-manager-library/pkg/controllermanager/examples/apis \
  github.com/gardener/controller-manager-library/pkg/controllermanager/examples/apis \
  "example:v1alpha1,v1beta1" \
  --go-header-file "$(dirname $0)/LICENSE_BOILERPLATE.txt"

echo "*** generate conversion ($PWD)"
bash "${PROJECT_ROOT}"/vendor/k8s.io/code-generator/generate-internal-groups.sh \
  conversion \
  github.com/gardener/controller-manager-library/pkg/controllermanager/examples/client \
  github.com/gardener/controller-manager-library/pkg/controllermanager/examples/apis \
  github.com/gardener/controller-manager-library/pkg/controllermanager/examples/apis \
  "example:v1alpha1,v1beta1" \
  --extra-peer-dirs=github.com/gardener/controller-manager-library/pkg/controllermanager/examples/apis/example,github.com/gardener/controller-manager-library/pkg/controllermanager/examples/apis/example/v1alpha1,github.com/gardener/controller-manager-library/pkg/controllermanager/examples/apis/example/v1beta1,k8s.io/apimachinery/pkg/apis/meta/v1,k8s.io/apimachinery/pkg/conversion,k8s.io/apimachinery/pkg/runtime \
  --go-header-file "$(dirname $0)/LICENSE_BOILERPLATE.txt"
echo "*** done"