// Code generated by client-gen. DO NOT EDIT.

package fake

import (
	v1alpha1 "github.com/gardener/controller-manager-library/pkg/client/gardenextensions/clientset/versioned/typed/extensions/v1alpha1"
	rest "k8s.io/client-go/rest"
	testing "k8s.io/client-go/testing"
)

type FakeExtensionsV1alpha1 struct {
	*testing.Fake
}

func (c *FakeExtensionsV1alpha1) ControlPlanes(namespace string) v1alpha1.ControlPlaneInterface {
	return &FakeControlPlanes{c, namespace}
}

func (c *FakeExtensionsV1alpha1) DNSs(namespace string) v1alpha1.DNSInterface {
	return &FakeDNSs{c, namespace}
}

// RESTClient returns a RESTClient that is used to communicate
// with API server by this client implementation.
func (c *FakeExtensionsV1alpha1) RESTClient() rest.Interface {
	var ret *rest.RESTClient
	return ret
}
