// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// ControlPlaneListerExpansion allows custom methods to be added to
// ControlPlaneLister.
type ControlPlaneListerExpansion interface{}

// ControlPlaneNamespaceListerExpansion allows custom methods to be added to
// ControlPlaneNamespaceLister.
type ControlPlaneNamespaceListerExpansion interface{}

// DNSListerExpansion allows custom methods to be added to
// DNSLister.
type DNSListerExpansion interface{}

// DNSNamespaceListerExpansion allows custom methods to be added to
// DNSNamespaceLister.
type DNSNamespaceListerExpansion interface{}
