/*
 * SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
 *
 * SPDX-License-Identifier: Apache-2.0
 *
 */

package types

// StandardObjectStatus is simple default status consisting of a state and message field
type StandardObjectStatus struct {
	// +optional
	State string `json:"state,omitempty"`
	// +optional
	Message string `json:"message,omitempty"`
}

// DeepCopyInto is an autogenerated deepcopy function, copying the receiver, writing into out. in must be non-nil.
func (in *StandardObjectStatus) DeepCopyInto(out *StandardObjectStatus) {
	*out = *in
	return
}

// DeepCopy is an autogenerated deepcopy function, copying the receiver, creating a new StandardObjectStatus.
func (in *StandardObjectStatus) DeepCopy() *StandardObjectStatus {
	if in == nil {
		return nil
	}
	out := new(StandardObjectStatus)
	in.DeepCopyInto(out)
	return out
}
